blueprint:
  name: Frost Warning – BOM
  description: >
    Send a notification in the morning if BOM temperature is below a threshold 
    and the dew point is close enough to indicate frost.
  domain: automation
  input:
    temperature_sensor:
      name: BOM Temperature Sensor
      description: The BOM temperature entity (e.g., sensor.bom_temperature_canberra)
      selector:
        entity:
          domain: sensor
    dew_point_sensor:
      name: BOM Dew Point Sensor
      description: The BOM dew point entity (e.g., sensor.bom_dew_point_canberra)
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Notification Target
      description: The device to notify
      selector:
        device:
          integration: mobile_app
    trigger_time:
      name: Time to check
      description: Time of day to trigger the frost check
      default: "05:00:00"
      selector:
        time:
    temperature_threshold:
      name: Temperature Threshold (°C)
      description: If temperature is below this value, check for frost risk
      default: 2
      selector:
        number:
          min: -10
          max: 10
          unit_of_measurement: °C
          mode: slider
    dew_point_gap:
      name: Max Difference Between Temp and Dew Point (°C)
      description: If temp - dew point is less than this, frost is likely
      default: 2
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: °
